/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "mathimatical_operations/core_operations.h"

/*=======Structure Used By Test Runner=====*/
struct UnityRunTestParameters
{
  UnityTestFunction func;
  const char* name;
  UNITY_LINE_TYPE line_num;
};

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_unity_is_working(void);
extern void test_complex_initialize(void);
extern void test_quantom_reg_create_initializes_zero_state(void);
extern void test_quantom_reg_create_allocates_full_state(void);
extern void test_quantom_free_accepts_null(void);
extern void test_complex_add(void);
extern void test_complex_multiply(void);
extern void test_complex_conjugate(void);
extern void test_quantom_hadamard(void);
extern void test_quantom_x(void);
extern void test_quantom_z(void);
extern void test_quantom_y(void);
extern void test_quantom_s(void);
extern void test_quantom_cnot(void);
extern void test_controlled_phase(void);
extern void test_swap(void);
extern void test_toffoli(void);
extern void test_hadamar_all(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}
/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("tests/Quantom_test.c");

  struct UnityRunTestParameters run_test_params_arr[18];

  run_test_params_arr[0].func = test_unity_is_working;
  run_test_params_arr[0].name = "test_unity_is_working";
  run_test_params_arr[0].line_num = 8;
  run_test_params_arr[1].func = test_complex_initialize;
  run_test_params_arr[1].name = "test_complex_initialize";
  run_test_params_arr[1].line_num = 9;
  run_test_params_arr[2].func = test_quantom_reg_create_initializes_zero_state;
  run_test_params_arr[2].name = "test_quantom_reg_create_initializes_zero_state";
  run_test_params_arr[2].line_num = 10;
  run_test_params_arr[3].func = test_quantom_reg_create_allocates_full_state;
  run_test_params_arr[3].name = "test_quantom_reg_create_allocates_full_state";
  run_test_params_arr[3].line_num = 11;
  run_test_params_arr[4].func = test_quantom_free_accepts_null;
  run_test_params_arr[4].name = "test_quantom_free_accepts_null";
  run_test_params_arr[4].line_num = 12;
  run_test_params_arr[5].func = test_complex_add;
  run_test_params_arr[5].name = "test_complex_add";
  run_test_params_arr[5].line_num = 13;
  run_test_params_arr[6].func = test_complex_multiply;
  run_test_params_arr[6].name = "test_complex_multiply";
  run_test_params_arr[6].line_num = 14;
  run_test_params_arr[7].func = test_complex_conjugate;
  run_test_params_arr[7].name = "test_complex_conjugate";
  run_test_params_arr[7].line_num = 15;
  run_test_params_arr[8].func = test_quantom_hadamard;
  run_test_params_arr[8].name = "test_quantom_hadamard";
  run_test_params_arr[8].line_num = 16;
  run_test_params_arr[9].func = test_quantom_x;
  run_test_params_arr[9].name = "test_quantom_x";
  run_test_params_arr[9].line_num = 17;
  run_test_params_arr[10].func = test_quantom_z;
  run_test_params_arr[10].name = "test_quantom_z";
  run_test_params_arr[10].line_num = 18;
  run_test_params_arr[11].func = test_quantom_y;
  run_test_params_arr[11].name = "test_quantom_y";
  run_test_params_arr[11].line_num = 19;
  run_test_params_arr[12].func = test_quantom_s;
  run_test_params_arr[12].name = "test_quantom_s";
  run_test_params_arr[12].line_num = 20;
  run_test_params_arr[13].func = test_quantom_cnot;
  run_test_params_arr[13].name = "test_quantom_cnot";
  run_test_params_arr[13].line_num = 21;
  run_test_params_arr[14].func = test_controlled_phase;
  run_test_params_arr[14].name = "test_controlled_phase";
  run_test_params_arr[14].line_num = 22;
  run_test_params_arr[15].func = test_swap;
  run_test_params_arr[15].name = "test_swap";
  run_test_params_arr[15].line_num = 23;
  run_test_params_arr[16].func = test_toffoli;
  run_test_params_arr[16].name = "test_toffoli";
  run_test_params_arr[16].line_num = 24;
  run_test_params_arr[17].func = test_hadamar_all;
  run_test_params_arr[17].name = "test_hadamar_all";
  run_test_params_arr[17].line_num = 25;

  for (int i = 0; i < 18; i++)
  {
    run_test(run_test_params_arr[i].func, run_test_params_arr[i].name, run_test_params_arr[i].line_num);
  }

  return UNITY_END();
}
